version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Ejecutando pruebas...
      - pytest --cov-fail-under=71 --cov=. -s --verbose tests/
      - echo Empaquetando artefacto...
      - zip -r build-output.zip .
  post_build:
    commands:
      - echo Artefacto empaquetado con éxito.
      - echo Subiendo artefacto a S3...
      - aws s3 cp build-output.zip s3://sancochoft-builds-prod/artefactos/build-output.zip
      - echo Artefacto subido a S3.

artifacts:
  files:
    - build-output.zip
  name: build-artifact-$(date +%Y%m%d%H%M%S)
