version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 816292901557.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t sancochoft/blacklist-app .
      - docker tag sancochoft/blacklist-app:latest 816292901557.dkr.ecr.us-east-1.amazonaws.com/sancochoft/blacklist-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push 816292901557.dkr.ecr.us-east-1.amazonaws.com/sancochoft/blacklist-app:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Blacklist-app-python-container","imageUri":"816292901557.dkr.ecr.us-east-1.amazonaws.com/sancochoft/blacklist-app:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"816292901557.dkr.ecr.us-east-1.amazonaws.com/sancochoft/blacklist-app:latest"}' > imageDetail.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
