services:
  blacklists:
    build: .
    depends_on:
      - blacklists_db
    ports:
      - "5000:5000"
    environment:
      RDS_DB_NAME: blacklists_db
      RDS_USERNAME: postgres
      RDS_PASSWORD: example
      RDS_PORT: 5432
      RDS_HOSTNAME: blacklists_db
      SECRET_TOKEN: qwerty
    networks:
      - app_net

  blacklists_db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: blacklists_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
