services:
  blacklists:
    build: .
    depends_on:
      - blacklists_db
    ports:
      - "5000:5000"
    environment:
      DB_NAME: blacklists_db
      DB_USER: postgres
      DB_PASSWORD: example
      DB_PORT: 5432
      DB_HOST: blacklists_db
      SECRET_TOKEN: qwerty
    networks:
      - app_net

  blacklists_db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: blacklists_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
